# fly.toml file generated for einviertel-auth on 2023-04-09T18:06:46+02:00

app = "einviertel-auth"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  JAVA_OPTS = "-Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0 -Djava.net.preferIPv6Addresses=true"
  KC_DB = "postgres"
  KC_HOSTNAME_STRICT = "false"
  KC_HTTP_ENABLED = "true"
  KC_PROXY = "edge"
  PROXY_ADDRESS_FORWARDING = "true"

[experimental]
  cmd = ["start", "--cache=ispn", "--cache-config-file=flyio-cache-config.xml"]

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
